# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cca2d00ad1c75fa45e8e781a959e01b3bf8490e198356a85ce360c9d3f0fe511f898bdb3c2b9143eba02981b19ef68b65a53a2123b7d722b09f9f88104a3dccd

test:
  secret_key_base: 0fb57b01569bdb3e51220e03150fb9f81ab7065f2e5b17e51047a0a511c2d5376efee687843262aa828e05acdd507c9fe9179dcaa65e904e7031933a1971b5d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
